import Head from 'next/head'
import { createClient } from 'next-sanity'
import Topnav from '../components/topnav'

export default function Home({ plants }) {
  return (
    <div>
      <Head>
        <title>Plantones</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/plantone-icon.ico" />
      </Head>

      <Topnav />
      <main>
        <h2>Plants</h2>
        {plants.length > 0 && (
          <ul>
            {plants.map((plant) => (
              <li key={plant._id}>{plant?.commonName}</li>
            ))}
          </ul>
        )}
      </main>
    </div>
  )
}

const client = createClient({
  projectId: process.env.SANITY_ID,
  dataset: 'production',
  apiVersion: '2022-03-25',
  useCdn: false,
})

export async function getStaticProps() {
  const plants = await client.fetch(`*[_type == "plants"]`)

  return {
    props: {
      plants,
    },
  }
}
