import Head from 'next/head'
import { createClient } from 'next-sanity'
import Topnav from '../components/topnav'
import Grid from '../components/grid'


export default function Home({ plants }) {
  return (
    <div>
      <Head>
        <title>Plantones</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/plantone-icon.ico" />
      </Head>

      <Topnav />
      <Grid props={plants} />
    </div>
  )
}

const client = createClient({
  projectId: process.env.SANITY_ID,
  dataset: 'production',
  apiVersion: '2022-03-25',
  useCdn: false,
})

export async function getStaticProps() {
  const plants = await client.fetch(`*[_type == "plants"]`)

  return {
    props: {
      plants,
    },
  }
}
